jobs:
  include:
    - stage: Python-tests
      language: python
      python: "3.6"
      install:
          - pip install --upgrade pip
          - pip install coverage
          - pip install -r requirements.txt
      before_script:
          - uname -a
          - printenv | sort
      script:
          - date
          - sh run_tests.sh

    - stage: Postman
      language: node_js
      node_js: "8.9"
      script:
        - echo Install newman to run Postman tests
        - npm install newman
        - node_modules/.bin/newman run Postman.json
