jobs:
  include:
    - stage: Python-tests
      language: python
      python: "3.6"
      install:
          - pip install --upgrade pip
          - pip install coverage
          - pip install -r requirements.txt
      before_script:
          - uname -a
          - printenv | sort
      script:
          - date
          - python backend/tests.py

    - stage: Postman
      language: node_js
      node_js: "8.9"
      script:
        - echo Install newman to run Postman tests
        - npm install newman
        - node_modules/.bin/newman run Postman.json

    - stage: Mocha
      language: node_js
      node_js: "8.9"
      script:
        - echo Mocha tests
        - npm install --prefix frontend
        - npm run --prefix frontend &

notifications:
  email: false
  slack:
    rooms:
      - cs373group-spring2018:sCnIokOODJPNDix3PTLqFPKy#commits
    on_failure: always
    on_success: always